[package]
name = "system-pulse"
version = "0.1.0"
edition.workspace = true
license = "GPL-3.0-or-later"
publish = false

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
gpui-base.workspace = true
gpui-component.workspace = true
serde_json.workspace = true
smol.workspace = true
system-pulse-model = { path = "model" }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
